#!/bin/bash

. $(dirname $0)/set-jdk-version.sh

$(dirname $0)/gradle assemble || exit 1

export SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-"development"}
LOGBACK_CONFIG=${LOGBACK_CONFIG:-"config/logback.xml"}

JAVAOPTS=${JAVAOPTS:-""}
if [[ -n $LOGBACK_CONFIG ]]
then
    JAVAOPTS="$JAVAOPTS -Dlogging.config=$LOGBACK_CONFIG"
fi
exec java $JAVAOPTS -jar build/libs/bricolage-streaming-preprocessor-LATEST-boot.jar "$@"
